// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.u64().primaryKey(),
  player: __t.identity(),
  name: __t.string(),
  depth: __t.u32(),
  killedBy: __t.string().name("killed_by"),
  x: __t.f32(),
  z: __t.f32(),
  runSeed: __t.u64().name("run_seed"),
  buildVersion: __t.string().name("build_version"),
  at: __t.timestamp(),
});
