// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.u64().primaryKey(),
  playerId: __t.u64().name("player_id"),
  seed: __t.u64(),
  buildVersion: __t.string().name("build_version"),
  depth: __t.u32(),
  kills: __t.u32(),
  name: __t.string(),
  tape: __t.string(),
  status: __t.string(),
  at: __t.timestamp(),
});
