// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export const Death = __t.object("Death", {
  id: __t.u64(),
  playerId: __t.u64(),
  name: __t.string(),
  depth: __t.u32(),
  killedBy: __t.string(),
  x: __t.f32(),
  z: __t.f32(),
  runSeed: __t.u64(),
  buildVersion: __t.string(),
  at: __t.timestamp(),
});
export type Death = __Infer<typeof Death>;

export const Identity = __t.object("Identity", {
  id: __t.identity(),
  playerId: __t.u64(),
  provider: __t.string(),
  linkedAt: __t.timestamp(),
});
export type Identity = __Infer<typeof Identity>;

export const LinkCode = __t.object("LinkCode", {
  code: __t.string(),
  playerId: __t.u64(),
  expiresAtMicros: __t.u64(),
});
export type LinkCode = __Infer<typeof LinkCode>;

export const PendingRun = __t.object("PendingRun", {
  id: __t.u64(),
  playerId: __t.u64(),
  seed: __t.u64(),
  buildVersion: __t.string(),
  depth: __t.u32(),
  kills: __t.u32(),
  name: __t.string(),
  tape: __t.string(),
  status: __t.string(),
  at: __t.timestamp(),
});
export type PendingRun = __Infer<typeof PendingRun>;

export const Player = __t.object("Player", {
  id: __t.u64(),
  displayName: __t.string(),
  createdAt: __t.timestamp(),
});
export type Player = __Infer<typeof Player>;

