// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export const Death = __t.object("Death", {
  id: __t.u64(),
  player: __t.identity(),
  name: __t.string(),
  depth: __t.u32(),
  killedBy: __t.string(),
  x: __t.f32(),
  z: __t.f32(),
  runSeed: __t.u64(),
  buildVersion: __t.string(),
  at: __t.timestamp(),
});
export type Death = __Infer<typeof Death>;

