// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import { type Infer as __Infer } from "spacetimedb";

// Import all reducer arg schemas
import IssueLinkCodeReducer from "../issue_link_code_reducer";
import RedeemLinkCodeReducer from "../redeem_link_code_reducer";
import ReportDeathReducer from "../report_death_reducer";
import SetDisplayNameReducer from "../set_display_name_reducer";
import SubmitRunReducer from "../submit_run_reducer";

export type IssueLinkCodeParams = __Infer<typeof IssueLinkCodeReducer>;
export type RedeemLinkCodeParams = __Infer<typeof RedeemLinkCodeReducer>;
export type ReportDeathParams = __Infer<typeof ReportDeathReducer>;
export type SetDisplayNameParams = __Infer<typeof SetDisplayNameReducer>;
export type SubmitRunParams = __Infer<typeof SubmitRunReducer>;

