// AUTO-GENERATED by scripts/gen-patchlog.ts — DO NOT EDIT.
// Regenerated on every build from commits that carry a Patch-summary
// trailer. See CLAUDE.md "Commit message format" for the contract.

export const GENERATED_PATCHLOG = [
  {
    "version": "Build 34",
    "date": "2026-07-18",
    "entries": [
      {
        "tag": "content",
        "text": "The dead left more than one thing behind. Find another of theirs and the deep will say so.",
        "area": [
          "content",
          "loot",
          "ui"
        ]
      },
      {
        "tag": "add",
        "text": "Your reliquary has a page of its own now. The collection grows by domain, and every piece remembers whose it was.",
        "area": [
          "ui",
          "content"
        ]
      },
      {
        "tag": "content",
        "text": "The dead no longer drop boots. Their belongings are relics now — take one and it takes a piece of them into you.",
        "area": [
          "content",
          "loot"
        ]
      },
      {
        "tag": "fix",
        "text": "Trap rooms spring only once you are well and truly inside. Being sealed out of your own ambush was never the deal.",
        "area": [
          "level"
        ]
      }
    ]
  },
  {
    "version": "Build 33",
    "date": "2026-07-10",
    "entries": [
      {
        "tag": "add",
        "text": "Take a dead thing's belonging and the deep tells you whose it was. It is yours now.",
        "area": [
          "ui",
          "loot"
        ]
      },
      {
        "tag": "content",
        "text": "The dead leave their thirst bound in cord and bone. Pick one up and it beats when yours does.",
        "area": [
          "content",
          "loot"
        ]
      },
      {
        "tag": "fix",
        "text": "The bone niches glow when you near them now, and give up their dead's leavings onto the floor instead of swallowing them.",
        "area": [
          "level",
          "content"
        ]
      },
      {
        "tag": "add",
        "text": "A well-timed roll now vaults a fallen pillar. Misjudge the far side and the stone keeps you honest.",
        "area": [
          "combat",
          "controls",
          "level"
        ]
      },
      {
        "tag": "fix",
        "text": "You stop drifting around behind the loading dark — controls hold until the floor is actually under you.",
        "area": [
          "controls"
        ]
      }
    ]
  },
  {
    "version": "Build 32",
    "date": "2026-07-09",
    "entries": [
      {
        "tag": "tune",
        "text": "Small rooms hold one prize now, not a pile. A fire and a locked chest stop fighting for the same closet — the deep spreads its gifts out.",
        "area": [
          "level"
        ]
      },
      {
        "tag": "content",
        "text": "The bone shelves give up their secrets now — search one and the dead share what they carried down. The altars that just stood there have stopped standing there.",
        "area": [
          "level",
          "content"
        ]
      },
      {
        "tag": "tune",
        "text": "Loot sits square to the room now — turned toward the door, but never at a drunken angle.",
        "area": [
          "level"
        ]
      },
      {
        "tag": "fix",
        "text": "The treasure stops trying to sit in the altar's lap. Big authored things claim their ground first; the loot gives them room.",
        "area": [
          "level"
        ]
      },
      {
        "tag": "tune",
        "text": "Drink in peace — a nervous second tap won't spill it, only a dodge or a swing will. Loot turns to face the door you came through, and you no longer descend into a chest sitting on your toes.",
        "area": [
          "combat",
          "level",
          "controls"
        ]
      },
      {
        "tag": "tune",
        "text": "The fire finds room to breathe now instead of jamming itself into a corner where you can barely reach it.",
        "area": [
          "level",
          "atmosphere"
        ]
      },
      {
        "tag": "tune",
        "text": "The slumped dead find a wall to lean on now, and the things meant for the middle of a room actually sit in the middle of it.",
        "area": [
          "level",
          "atmosphere"
        ]
      },
      {
        "tag": "tune",
        "text": "Walk into a room and the chest is looking at you now — set to face the way you came in, not shoved at the wall at random.",
        "area": [
          "level"
        ]
      },
      {
        "tag": "tune",
        "text": "Gold chests go back to being a rumor. The deep stops handing them out like bread, and there is less of everything to trip over.",
        "area": [
          "level",
          "content"
        ]
      },
      {
        "tag": "tune",
        "text": "Fewer dead down here now. The ones you find, you were meant to find."
      },
      {
        "tag": "tune",
        "text": "The card hangs over the thing itself now, like a label on a hook — you read it where it lies.",
        "area": [
          "ui"
        ]
      },
      {
        "tag": "add",
        "text": "Look at a thing on the floor and it tells you what it is now — the whole of it, not a half-line. Whether you take it is still on you.",
        "area": [
          "ui",
          "controls"
        ]
      },
      {
        "tag": "content",
        "text": "The gold chest stops being a bigger box. It sits in its own light now, horned and sigil-marked — the kind of thing you cross a room for, and maybe shouldn't open.",
        "area": [
          "level",
          "atmosphere",
          "content"
        ]
      },
      {
        "tag": "tune",
        "text": "The dead lie where they fell now — slumped against the walls, crawling on the open stone. Fewer of them, and every one put there on purpose.",
        "area": [
          "level",
          "content",
          "atmosphere"
        ]
      },
      {
        "tag": "tune",
        "text": "Chests stop breeding in the corners. A floor gets a few, set where they were meant to sit — and a gold one, when it comes, holds court.",
        "area": [
          "level",
          "content"
        ]
      },
      {
        "tag": "add",
        "text": "The good boxes are locked now. Silver and gold want a key; wood opens for anyone. Spend the key on the wrong one and the dungeon keeps it anyway.",
        "area": [
          "content",
          "level"
        ]
      },
      {
        "tag": "tune",
        "text": "The dead stop coughing up swords. Coins, mostly — the odd key — and now and then nothing at all. What you actually want is locked in a box somewhere deeper.",
        "area": [
          "combat",
          "content"
        ]
      }
    ]
  },
  {
    "version": "Build 31",
    "date": "2026-07-08",
    "entries": [
      {
        "tag": "tune",
        "text": "The numbers come back to earth. A heart is worth something again, a heal is a mercy not a flood, and the things down here take more than a single breath to put down.",
        "area": [
          "combat",
          "content"
        ]
      },
      {
        "tag": "add",
        "text": "The rites stop being one trick. A spell is a handful of small cruelties stacked together now — erupt, drain, brand, or simply become something worse for a while.",
        "area": [
          "combat",
          "content",
          "ui"
        ]
      },
      {
        "tag": "tech",
        "text": "The satchel forgets the ten pockets it never needed. A blade, a thing in the off-hand, a garment — and everything else you drag up from the dark simply clings to you.",
        "area": [
          "ui",
          "content"
        ]
      },
      {
        "tag": "tune",
        "text": "Hammers land on the new footing — sweep, sweep, and an overhead that catches three. Hold it and the ground remembers the blow.",
        "area": [
          "combat",
          "weapons"
        ]
      },
      {
        "tag": "tune",
        "text": "Blades keep a rhythm now — you cannot spam them faster than they mean to move. Hold one back and it strikes without winding up twice.",
        "area": [
          "combat",
          "weapons"
        ]
      },
      {
        "tag": "add",
        "text": "Hold the blade back and it lands heavier — a plunge, a driving cut. Strike out of a dodge and it lunges. The dungeon notices the ones who move like that.",
        "area": [
          "combat",
          "weapons"
        ]
      },
      {
        "tag": "tune",
        "text": "Swords learn the new footwork too — a diagonal cut into its mirror into a thrust, a lunge when you press in, a wide sweep when you sidestep.",
        "area": [
          "combat",
          "weapons"
        ]
      },
      {
        "tag": "tune",
        "text": "Every dagger learns the new footwork — thrust, cut, and a finishing flurry, and it leans where you step. The needle remembers how the Harrow moves.",
        "area": [
          "combat",
          "weapons"
        ]
      },
      {
        "tag": "add",
        "text": "A new blade in the dark — the Harrow does not cut, it rips. Thrust, cut, or shred, depending which way you move. It learns your feet.",
        "area": [
          "combat",
          "weapons"
        ]
      }
    ]
  },
  {
    "version": "Build 30",
    "date": "2026-07-07",
    "entries": [
      {
        "tag": "add",
        "text": "Bleed a thing to death and its wound calls to those beside it. Kill the bleeding and you drink. A pack can unmake itself, if you make the first cut.",
        "area": [
          "combat",
          "content"
        ]
      },
      {
        "tag": "tune",
        "text": "The vials are gone from the dark. Your only mercy is the fire — and it mends you whole, once, before it forgets you.",
        "area": [
          "combat",
          "content"
        ]
      },
      {
        "tag": "content",
        "text": "The Howling Edge is a warden's blade now — you take it off something that earned the name, never from a lucky box.",
        "area": [
          "content",
          "level"
        ]
      },
      {
        "tag": "content",
        "text": "Deep halls stand as wrecks now — a snapped column, its fallen half beside it — and each room dresses to its purpose: the arena bare, the storeroom cluttered.",
        "area": [
          "level",
          "atmosphere"
        ]
      },
      {
        "tag": "tune",
        "text": "The dungeon keeps its thresholds clear and stands its pillars in ranks now — rooms look built, not spilled.",
        "area": [
          "level",
          "atmosphere"
        ]
      },
      {
        "tag": "fix",
        "text": "Escape now backs out one step at a time — shrug off the note, then close the menu, and only then does it open one. No more double-takes.",
        "area": [
          "controls",
          "ui"
        ]
      },
      {
        "tag": "fix",
        "text": "The mage staff no longer drags the whole world into the dark when you draw it — its light was never meant to be the last thing you see.",
        "area": [
          "combat",
          "tech"
        ]
      },
      {
        "tag": "fix",
        "text": "Smashed pots stop haunting the floor with an invisible wall — the ground they stood on is yours again.",
        "area": [
          "level",
          "controls"
        ]
      },
      {
        "tag": "content",
        "text": "The clay pots scatter fresh each descent now, never the same corner twice — and never underfoot of what matters.",
        "area": [
          "level",
          "atmosphere"
        ]
      },
      {
        "tag": "content",
        "text": "The deep stages a prize and a bargain in every room worth the trouble now, not just a chosen few.",
        "area": [
          "level",
          "content"
        ]
      }
    ]
  },
  {
    "version": "Build 29",
    "date": "2026-07-06",
    "entries": [
      {
        "tag": "tune",
        "text": "The dungeon stops handing you the same trick twice a floor — one deal, chosen to fit the depth, and never a second heal fountain to spoil it.",
        "area": [
          "level",
          "content"
        ]
      },
      {
        "tag": "add",
        "text": "The good find sits where the room means your eye to fall now — a real prize on the dais, and never the same twice.",
        "area": [
          "level",
          "content"
        ]
      },
      {
        "tag": "tune",
        "text": "The fire keeps to the far corners now — never the doorway, never the stairs. You will come to it.",
        "area": [
          "level",
          "atmosphere"
        ]
      }
    ]
  },
  {
    "version": "Build 28",
    "date": "2026-07-05",
    "entries": [
      {
        "tag": "fix",
        "text": "The first desperate swig no longer stutters. The dungeon was never going to make drinking easy, but it will make it smooth.",
        "area": [
          "combat",
          "tech"
        ]
      },
      {
        "tag": "tech",
        "text": "Every open flame on the floor is now a single stroke of the dungeon's brush.",
        "area": [
          "atmosphere",
          "tech"
        ]
      }
    ]
  }
] as const;
