// AUTO-GENERATED by scripts/gen-patchlog.ts — DO NOT EDIT.
// Regenerated on every build from the git history. Edit commit
// subjects (or scripts/gen-patchlog.ts) to change what appears here.

export const GENERATED_PATCHLOG = [
  {
    "version": "Build 6",
    "date": "2026-05-29",
    "entries": [
      {
        "tag": "add",
        "text": "Debug capture"
      },
      {
        "tag": "tune",
        "text": "Debug capture tool (?debug=1): one-tap glitch reports"
      },
      {
        "tag": "tune",
        "text": "Vases shatter in one hit"
      }
    ]
  },
  {
    "version": "Build 5",
    "date": "2026-05-28",
    "entries": [
      {
        "tag": "tune",
        "text": "Generic passage clearance + reachability safety net"
      },
      {
        "tag": "tune",
        "text": "Progression safety net: chests in corridors lose collision"
      },
      {
        "tag": "fix",
        "text": "Door + stair opening fixes; doorframe lintel above doors"
      },
      {
        "tag": "content",
        "text": "Torch audio: subtle pops — quieter, rarer, gentler attack"
      },
      {
        "tag": "tune",
        "text": "Hammer combo: swing-right → swing-left → smash"
      },
      {
        "tag": "content",
        "text": "Torch audio: drop fizz bed, boost crackle pops to foreground"
      },
      {
        "tag": "content",
        "text": "Add acid-spitter ooze — blue ranged ooze variant"
      },
      {
        "tag": "content",
        "text": "Torch audio: warm fizz bed under softer pops, not Geiger clicks"
      },
      {
        "tag": "add",
        "text": "PWA updates"
      },
      {
        "tag": "fix",
        "text": "Hammer side-swings: fix rotZ sign — head now leads, not haft"
      },
      {
        "tag": "tune",
        "text": "Hammer side-swings: parabolic forward arc, not in-place leaning"
      },
      {
        "tag": "content",
        "text": "Lit-fixture pool"
      },
      {
        "tag": "tune",
        "text": "play.ts: --headed flag for live watching"
      },
      {
        "tag": "content",
        "text": "Quieter, more deliberate brazier + pike placement"
      },
      {
        "tag": "tune",
        "text": "Hammer side-swings: wide haymaker arc, body drifts through"
      },
      {
        "tag": "tune",
        "text": "Shift stairs SIDEWAYS too, not just along descent"
      },
      {
        "tag": "tune",
        "text": "Combo anims: flatten hammer side-swings, push sword slash-right forward"
      },
      {
        "tag": "tune",
        "text": "Combo anims: rising sword slash-right, head-led hammer side-smashes"
      },
      {
        "tag": "fix",
        "text": "Fix X-walls"
      },
      {
        "tag": "content",
        "text": "Drop the three candles from the healing fountain shrine"
      },
      {
        "tag": "tune",
        "text": "Finisher trigger: scaffold on-finisher damage modifier"
      },
      {
        "tag": "tune",
        "text": "Bot + npm run play: autonomous episodes with transcripts"
      },
      {
        "tag": "tune",
        "text": "Combos"
      },
      {
        "tag": "fix",
        "text": "Fix X-walls in mid-room: drop terminus end-caps"
      },
      {
        "tag": "tune",
        "text": "Combo: queue chains through whole combo, stops at finisher"
      },
      {
        "tag": "content",
        "text": "Lantern flame stack + iron brazier + cresset pike + frustum cull"
      },
      {
        "tag": "tune",
        "text": "Combo: one-hop press buffer — chain next step, not the whole combo"
      },
      {
        "tag": "tune",
        "text": "Dagger combo: drop press buffering, slow timings ~25%"
      },
      {
        "tag": "tune",
        "text": "Combo: whoosh + event fire per step, widen dagger slash"
      },
      {
        "tag": "fix",
        "text": "Fix X-shaped wall artifact from isolated '#' tiles"
      },
      {
        "tag": "content",
        "text": "Weapon combos: dagger stab → slash → stab-stab"
      },
      {
        "tag": "tune",
        "text": "Annotated screenshots: harness.screenshot({annotated:true})"
      },
      {
        "tag": "content",
        "text": "Robust preview labels + inspect-to-reveal stats on blood altar"
      },
      {
        "tag": "tune",
        "text": "Update suppression"
      },
      {
        "tag": "fix",
        "text": "Continue Run fix: depth was off by one + seeded jumps"
      },
      {
        "tag": "tune",
        "text": "Harness v1: ?harness=1 boot + observation + action injection"
      },
      {
        "tag": "fix",
        "text": "Item preview labels: fixed size, no clamp, just clip off-screen"
      },
      {
        "tag": "fix",
        "text": "Fix character-screen build: unspentLabel typing + appendChild"
      },
      {
        "tag": "tune",
        "text": "Character system V1: combat math hookup"
      },
      {
        "tag": "tune",
        "text": "CHARACTER screen — read your build, spend points at safe rooms"
      },
      {
        "tag": "tune",
        "text": "Character system V1: attributes + proficiencies (tracking layer)"
      },
      {
        "tag": "content",
        "text": "Weapon anims: stab-stab dagger, head-first hammer, scaled item labels"
      },
      {
        "tag": "tune",
        "text": "Desktop"
      },
      {
        "tag": "content",
        "text": "Weapon classes: dagger stab, sword slash, hammer smash"
      },
      {
        "tag": "fix",
        "text": "Fix build: remove duplicate Seg type in parseTileMap"
      },
      {
        "tag": "tune",
        "text": "Death sequence: collapse onto side + dark fade + breathing epitaph"
      },
      {
        "tag": "tune",
        "text": "Stair clutter"
      }
    ]
  }
] as const;
