// AUTO-GENERATED by scripts/gen-patchlog.ts — DO NOT EDIT.
// Regenerated on every build from commits that carry a Patch-summary
// trailer. See CLAUDE.md "Commit message format" for the contract.

export const GENERATED_PATCHLOG = [
  {
    "version": "Build 7",
    "date": "2026-06-12",
    "entries": [
      {
        "tag": "add",
        "text": "Blood flies the way it was struck, every creature spills its own colour, and old violence dries brown by the time you walk back through.",
        "area": [
          "combat",
          "atmosphere",
          "content"
        ]
      }
    ]
  },
  {
    "version": "Build 6",
    "date": "2026-06-11",
    "entries": [
      {
        "tag": "fix",
        "text": "Mobs bleed where they stand and die. Vigor arrives as vigor, prices cut to the bone, and the mouse knows its place.",
        "area": [
          "combat",
          "ui",
          "atmosphere"
        ]
      },
      {
        "tag": "fix",
        "text": "Spilt blood finally stains the stone. The floors were drinking it in secret.",
        "area": [
          "atmosphere",
          "combat"
        ]
      },
      {
        "tag": "fix",
        "text": "Nothing may touch you between sitting and standing. The dungeon waits its turn.",
        "area": [
          "controls",
          "combat"
        ]
      },
      {
        "tag": "tune",
        "text": "Waking now swims into focus — and the dungeon saves the heavy eyelids for the mornings you earned.",
        "area": [
          "ui",
          "atmosphere"
        ]
      },
      {
        "tag": "fix",
        "text": "You wake the way the living do — eyes first, then legs. And your sword arm answers even when stairs are watching.",
        "area": [
          "controls",
          "ui",
          "level"
        ]
      },
      {
        "tag": "fix",
        "text": "You truly wake at the fire now — seated, facing it, rising.",
        "area": [
          "level",
          "controls"
        ]
      },
      {
        "tag": "fix",
        "text": "You wake facing the fire now, the stairs respect the wall, and the first chamber stops pretending to be a depth.",
        "area": [
          "level",
          "ui",
          "controls"
        ]
      },
      {
        "tag": "fix",
        "text": "The third rune learns to drown properly.",
        "area": [
          "ui"
        ]
      },
      {
        "tag": "add",
        "text": "Every floor now begins seated at a fire, and the fire finally answers: tend it, turn the wick, teach your eyes what the dark allows.",
        "area": [
          "ui",
          "atmosphere",
          "level",
          "controls"
        ]
      },
      {
        "tag": "add",
        "text": "The dungeon grows dials — brightness, torchlight strength and reach, all yours to turn. The dark keeps its opinion.",
        "area": [
          "ui",
          "atmosphere"
        ]
      },
      {
        "tag": "fix",
        "text": "The bone pile by the bonfire was never a shrine. It was arithmetic. The dead rest properly now.",
        "area": [
          "combat",
          "level"
        ]
      },
      {
        "tag": "fix",
        "text": "Floors with stairwells stop hallucinating their own colour. Blood now lands where blood was spilled.",
        "area": [
          "atmosphere",
          "level"
        ]
      },
      {
        "tag": "fix",
        "text": "The last levitating torch gives up and accepts a bracket.",
        "area": [
          "level",
          "atmosphere"
        ]
      },
      {
        "tag": "fix",
        "text": "Torches stop levitating in doorways. Mounting brackets exist for a reason.",
        "area": [
          "level",
          "atmosphere"
        ]
      },
      {
        "tag": "fix",
        "text": "The dead stop following you downstairs.",
        "area": [
          "combat",
          "level"
        ]
      },
      {
        "tag": "add",
        "text": "Blood stays where it landed now. The floors of busy rooms keep the receipts.",
        "area": [
          "atmosphere",
          "combat"
        ]
      },
      {
        "tag": "tune",
        "text": "The pickup outline speaks up.",
        "area": [
          "ui"
        ]
      },
      {
        "tag": "fix",
        "text": "The pickup outline is finally a line — the same thin line from every angle, on every shape.",
        "area": [
          "ui"
        ]
      },
      {
        "tag": "fix",
        "text": "The pickup glow slims back down to an outline instead of shrink-wrap.",
        "area": [
          "ui"
        ]
      },
      {
        "tag": "fix",
        "text": "The pickup glow hugs the blade it belongs to, all the way to the tip.",
        "area": [
          "ui",
          "atmosphere"
        ]
      },
      {
        "tag": "tune",
        "text": "The light pools deeper into the seams and the pillars stop pretending to be sponges.",
        "area": [
          "atmosphere"
        ]
      },
      {
        "tag": "tune",
        "text": "The crevices stop glittering and start drinking. Your lamp pours into every seam you pass.",
        "area": [
          "atmosphere"
        ]
      },
      {
        "tag": "tune",
        "text": "The seams in the worst floors stop glowing and start glistening. It is not an improvement in the way you mean.",
        "area": [
          "atmosphere"
        ]
      },
      {
        "tag": "fix",
        "text": "The bleeding walls actually bleed now. They were holding it in.",
        "area": [
          "atmosphere"
        ]
      },
      {
        "tag": "add",
        "text": "On the worst floors, the mortar has started to run. It moves toward the floor, the way everything here eventually does.",
        "area": [
          "atmosphere"
        ]
      },
      {
        "tag": "add",
        "text": "Some rooms stop lighting their walls and start engraving them — thin lines of fire where the mortar runs. A candle stub did this. Allegedly.",
        "area": [
          "atmosphere",
          "level"
        ]
      },
      {
        "tag": "tune",
        "text": "Torchlight reaches a little further still.",
        "area": [
          "atmosphere"
        ]
      },
      {
        "tag": "tune",
        "text": "The torches reach a little further into the dark. The dark remains unconvinced.",
        "area": [
          "atmosphere"
        ]
      },
      {
        "tag": "tune",
        "text": "Torchlight learns to pool instead of flood, the great halls hang chandeliers, and some corridors keep their dark. The lamp in your hand finally has a job again.",
        "area": [
          "atmosphere",
          "level"
        ]
      }
    ]
  },
  {
    "version": "Build 5",
    "date": "2026-06-10",
    "entries": [
      {
        "tag": "tune",
        "text": "The cracks keep their jagged tempers.",
        "area": [
          "atmosphere"
        ]
      },
      {
        "tag": "tune",
        "text": "The cracked bricks part along clean lines again, the way stone actually gives up.",
        "area": [
          "atmosphere"
        ]
      },
      {
        "tag": "tune",
        "text": "Some ceilings have already given up, and the cracks stop practicing their penmanship.",
        "area": [
          "atmosphere",
          "level"
        ]
      },
      {
        "tag": "tech",
        "text": "Thirty mobs now cost the renderer about as much as four used to. The dungeon notices no difference; your frame rate does.",
        "area": [
          "combat",
          "tech"
        ]
      },
      {
        "tag": "tune",
        "text": "The missing bricks gain depth and the cracks come back, each one different now. The wall has opinions about its age.",
        "area": [
          "atmosphere"
        ]
      },
      {
        "tag": "tech",
        "text": "The horde quietly sheds a third of its draw calls. It does not feel lighter; you might.",
        "area": [
          "combat",
          "atmosphere"
        ]
      },
      {
        "tag": "tune",
        "text": "The walls grow skirting, cornices and the occasional hollow where someone left a skull. The boxes stop admitting they are boxes.",
        "area": [
          "atmosphere",
          "level"
        ]
      },
      {
        "tag": "fix",
        "text": "The torches in a room finally agree on what colour the room is.",
        "area": [
          "atmosphere",
          "level"
        ]
      },
      {
        "tag": "fix",
        "text": "The god rays no longer share custody of their light pools, and the corridor lanterns climb out of the walls they were buried in.",
        "area": [
          "atmosphere",
          "level"
        ]
      },
      {
        "tag": "tech",
        "text": "The lantern's shadow learns to blink. Your thumbs get the frames it was hoarding.",
        "area": [
          "atmosphere",
          "tech"
        ]
      },
      {
        "tag": "fix",
        "text": "Light stops popping in and out of existence and learns to seep through doorways instead. The candles agree on a colour. Mostly.",
        "area": [
          "atmosphere",
          "level"
        ]
      },
      {
        "tag": "tech",
        "text": "The dungeon stops paying nine lights to stand around unlit. Frames arrive on time more often.",
        "area": [
          "atmosphere",
          "tech"
        ]
      },
      {
        "tag": "tune",
        "text": "The masonry settles. Bricks go missing, courses sit crooked, the floors wear where feet have been. The dungeon has been here longer than you.",
        "area": [
          "atmosphere",
          "level"
        ]
      },
      {
        "tag": "fix",
        "text": "The dungeon stops growing tiny pointless rooms, pillars step out of doorways, and the torchlight finally trembles like it means it. Health potions become a mercy, not a given.",
        "area": [
          "level",
          "content",
          "atmosphere"
        ]
      },
      {
        "tag": "add",
        "text": "Skeleton keys turn up in the deep, and locked cages with visible treasure start appearing. The boss seals upgraded from girders to actual chains. Bring bolt cutters. There are no bolt cutters.",
        "area": [
          "content",
          "level",
          "atmosphere"
        ]
      },
      {
        "tag": "add",
        "text": "A dry basin waits in a pale room. It accepts blood, coin, or the sword out of your hand. It does not accept questions.",
        "area": [
          "content",
          "level"
        ]
      },
      {
        "tag": "add",
        "text": "Three unlabeled phials enter the loot pool. The first sip is a question. The second is a confession.",
        "area": [
          "content",
          "combat"
        ]
      },
      {
        "tag": "tune",
        "text": "The dark talks now — a dry skull-rattle or a wet groan carries from across the room, and whatever's lurking stirs as you close on it. You hear them before you see them.",
        "area": [
          "atmosphere"
        ]
      },
      {
        "tag": "fix",
        "text": "The rats' front legs now attach to the rat. An inspector walks the bestiary so this stays true.",
        "area": [
          "content",
          "tech"
        ]
      },
      {
        "tag": "tune",
        "text": "Both wrists now answer to the arm they are attached to, at all times. Anatomical realism arrives unannounced, like most things down here.",
        "area": [
          "combat",
          "atmosphere"
        ]
      }
    ]
  }
] as const;
