// ── A CORRIDOR IS A SEGMENT WITH A JOB ───────────────────────────────────────
//
// Josh: *"I wonder how we can make the corridor generation truly awesome."*
//
// Measured first, over 72 generated floors and 601 corridor legs: every one is
// 3.0m tall, they come in exactly three widths, their length is a median 6.4m
// against a p90 of 8.5m, and the only thing that has ever stood in one is its
// own doorframe. 14% of the floor's area, doing one job — getting you there.
//
// The diagnosis is not "they need decorating". It is that a corridor is
// generated by CONNECT A TO B — geometry first — while a room stopped working
// that way when it got `roomType`. A room is a WORD first and a shape second,
// which is exactly why the content layer can extend rooms and cannot extend
// corridors. This file is the missing word.
//
// ── THE THREE THINGS A CORRIDOR CAN DO ───────────────────────────────────────
//
// HIDE — you cannot read the next room from this one. The dogleg already does
//   this on 75% of links, and it is the one thing corridors here already do
//   well. Nothing in this file changes it.
//
// SQUEEZE — the space changes what your BODY can do. This is the lever that was
//   worth nothing: at 2.2m wide and 3.0m tall you fight in a corridor exactly as
//   you fight in a room, same dodge, same arc, same spacing. It is also the only
//   entry on the list that touches combat feel, which is pillar #1 — so it is
//   the one this first pass is built around.
//
// PROMISE — you can see something you cannot reach yet. There is no map in this
//   game, so architecture is the only navigation the player gets. That is what
//   the GALLERY is for: tall and wide enough that it reads as somewhere, from a
//   long way off, before you can make out anything in it.
//
// ── HOW A TYPE IS CHOSEN ─────────────────────────────────────────────────────
//
// By the RUN IT HAS TO COVER, not by a free roll. Room placement decides how far
// apart two rooms are; the corridor reads that distance and picks the section
// that suits it. A squeeze you walk twelve metres down is tedious; a gallery
// four metres long is a doorway. So length variance — which was going to be its
// own pass — falls out of this one for free, and no new placement machinery is
// needed to get it.
//
// THE GATES ARE SET ON THE MEASURED RUN, not on a guess about it. `run` is the
// gap between the two rooms' exit points along the travel axis — measured over
// 339 connections: p10 4.2m, p25 5.0m, p50 6.0m, p75 6.9m, p90 7.6m, max 17.5m.
// (A first pass set these against the length of the whole DOGLEG, three times
// larger, and shipped galleries on 1% of links. Measuring the number you are
// actually going to branch on is the whole of the lesson.)
//
// So `squeeze.maxRun = 7.0` is about the third quartile and `gallery.minRun =
// 6.0` about the median: a squeeze is never a long trudge, a gallery is never a
// stub, and the middle band can be any of the three. The weights then land the
// mix near the 25 / 50 / 25 the width table already shipped — changing how OFTEN
// a section appears is a separate decision from giving it an identity, and doing
// both at once would make neither measurable.

import { archwayPassableHalfBand } from '../content/archway';
import { doorframePassableHalfBand } from '../content/doorframe';
import { gateAdmits } from './nav-grid';

export type CorridorTypeId = 'squeeze' | 'passage' | 'gallery';

/** What a corridor DOES to the player. Data, so the content and light layers
 *  can read intent rather than pattern-match on a width. */
export type CorridorIntent = 'squeeze' | 'pass' | 'promise';

export interface CorridorType {
  id: CorridorTypeId;
  intent: CorridorIntent;
  /** Clear width, metres. See MIN_WALKABLE_WIDTH before lowering any of these. */
  width: number;
  /** Ceiling height, metres. The frame models take this as `openHeight` and
   *  compress themselves to it, so a low section gets a low door for free. */
  height: number;
  /** The run lengths this section suits, metres. */
  minRun: number;
  maxRun: number;
  /** Relative pick weight among the types eligible for a given run. */
  weight: number;
}

/**
 * The widest body a corridor is SIZED FOR, metres — the wraith's 0.62.
 *
 * Deliberately one rung above the roster it has to carry. The widest thing that
 * actually roams a procgen floor today is the stoneguard at 0.55; the wraith is
 * flagged `miniboss` and is placed only in arena vaults, which do not use
 * polygon floors. But that exclusion is a PLACEMENT CONVENTION, not a property
 * of the mob — the day someone drops a wraith into a normal roll table, a
 * corridor sized to 0.55 wedges it in the door and it reads as a pathing bug.
 * Sizing to the widest body that exists costs nothing here (the narrowest
 * section is well above either number) and removes that whole failure.
 *
 * Bosses proper are out of scope: the marrow sovereign is 1.2 and boss depths
 * are vault-composed end to end (procgen.ts).
 *
 * Declared rather than imported so the layout generator does not pull the whole
 * enemy catalogue in. The test holds it against the REAL roster, so a new mob
 * wider than this fails the suite instead of quietly losing half the floor.
 */
export const WIDEST_ROAMER_RADIUS = 0.62;

/**
 * THE FLOOR UNDER `width`, AND IT IS DERIVED, NOT TYPED IN.
 *
 * The first version of this was the number 1.30, reasoned out as
 * `2 · (widest radius + gate slack)` — and it was wrong, because a corridor's
 * clear width is not its DOORWAY's clear width. Every opening wears a frame,
 * and an archway's columns stand about 4cm inside the jamb each side. Measured:
 * a wraith fits a bare 1.30m corridor and is blocked by the archway at the end
 * of it. That is a mob that follows you down a passage and stops in the door.
 *
 * So the floor is solved, at module load, from the SHIPPING functions — the
 * archway's own column offsets and the nav grid's own fit predicate — against
 * the widest body that can chase you. Retune the archway and this moves with
 * it; there is no constant left to fall out of date.
 */
function smallestAdmitting(radius: number): number {
  for (let w = 1.0; w < 4.0; w += 0.05) {
    const halfBand = Math.min(archwayPassableHalfBand(w), doorframePassableHalfBand(w));
    if (gateAdmits(halfBand, radius)) return Math.round(w * 100) / 100;
  }
  return 4.0;   // unreachable with any sane frame; degrade wide, never narrow
}
export const MIN_WALKABLE_WIDTH = smallestAdmitting(WIDEST_ROAMER_RADIUS);



export const CORRIDOR_TYPES: Readonly<Record<CorridorTypeId, CorridorType>> = {
  // Single file. No sidestep, no room for a swing arc, and nothing can get past
  // you — which cuts both ways, and that is the point. Short runs only: this is
  // a moment, not a journey.
  squeeze: {
    id: 'squeeze', intent: 'squeeze',
    // 1.55, not the 1.35 the floor allows: at the floor a wraith clears the
    // doorway by two centimetres, which is a jam waiting for the next archway
    // retune. The squeeze's read is mostly the 2.30m CEILING anyway — the one
    // dimension no mob has an opinion about — so the width buys margin instead.
    width: 1.55, height: 2.30,
    minRun: 0, maxRun: 7.0, weight: 0.25,
  },
  // The workhorse, and what every corridor in the game was until now.
  passage: {
    id: 'passage', intent: 'pass',
    width: 2.20, height: 3.00,
    minRun: 0, maxRun: Infinity, weight: 0.50,
  },
  // Wide and TALL — the height is most of the read. A fight can spill into one,
  // and from the far end of a dark room you can tell it is somewhere rather than
  // a hole. Long runs only; a short gallery is just a wide door.
  gallery: {
    id: 'gallery', intent: 'promise',
    width: 3.60, height: 4.60,
    minRun: 6.0, maxRun: Infinity, weight: 0.32,
  },
};

/** Every type, in declaration order. */
export const ALL_CORRIDOR_TYPES: readonly CorridorType[] = Object.values(CORRIDOR_TYPES);

/**
 * Which section suits a run of this length.
 *
 * `rand` is the floor's own build stream — deterministic per (depth, seed), like
 * everything else in the generator.
 */
export function corridorTypeFor(runLength: number, rand: () => number): CorridorType {
  const open = ALL_CORRIDOR_TYPES.filter((t) => runLength >= t.minRun && runLength <= t.maxRun);
  // `passage` has no gates, so this can only be empty if someone adds a type
  // with a hole in its range. Falling back is cheaper than a floor that throws.
  if (!open.length) return CORRIDOR_TYPES.passage;
  const total = open.reduce((s, t) => s + t.weight, 0);
  let roll = rand() * total;
  for (const t of open) { roll -= t.weight; if (roll <= 0) return t; }
  return open[open.length - 1];
}

/**
 * Pick a section from THE SPACE THE TWO WALLS CAN AFFORD.
 *
 * Josh, 2026-08-17: *"i want rooms to be connected, with bigger and smaller
 * corridors depending on how much space there is ... we dont have to adhere to any
 * legacy."*
 *
 * ── WHY RUN LENGTH WAS THE WRONG QUANTITY ────────────────────────────────────
 *
 * `corridorTypeFor` gates on how FAR the corridor runs, and its own call site
 * admits the number is an estimate whose "only job is to pick a word". Two things
 * are wrong with it now:
 *
 *   1. A GOOD ROUTER MINIMISES IT. Anchor-aligned placement puts two walls
 *      opposite each other, facing walls give straight corridors, and straight is
 *      short — so the long-run sections became unreachable. `squeeze` fell to 1.3%
 *      of corridors and the old per-section floor fired as though that were a
 *      regression. A vocabulary keyed to a quantity the solver is trying to reduce
 *      will always drain as the solver improves.
 *   2. IT SAYS NOTHING ABOUT THE PLACE. How long a passage is has no bearing on
 *      how wide it can be; a 20m run between two cramped walls cannot be a gallery
 *      and a 4m one between two long walls easily can.
 *
 * ── WHAT SPACE GIVES INSTEAD ─────────────────────────────────────────────────
 *
 * An anchor already declares a width RANGE — the most its wall can host after
 * corner clearance (level/anchors.ts). So the widest section a link can carry is
 * simply what BOTH ends can afford, and that is a fact about the architecture
 * rather than about the pathfinder. A pocket hung off a stub wall gets a squeeze
 * because it cannot get anything else; two long walls get a gallery because they
 * can.
 *
 * It also restores variety from a source routing does not fight. Room shapes vary,
 * so wall lengths vary, so affordable widths vary — and no amount of route
 * optimisation shortens a wall.
 *
 * Weights are kept among the ELIGIBLE sections, so the mix stays authored rather
 * than always taking the widest thing that fits.
 */
export function corridorTypeForSpace(affordable: number, rand: () => number): CorridorType {
  const open = ALL_CORRIDOR_TYPES.filter((t) => t.width <= affordable);
  // Nothing fits: hand back the narrowest section rather than inventing one. The
  // router still has the final say and will decline if the walls truly cannot
  // carry it — a declined link is a reroll, an invented width is a wall clipping
  // a corridor for the rest of the floor's life.
  if (!open.length) {
    return ALL_CORRIDOR_TYPES.reduce((m, t) => (t.width < m.width ? t : m), ALL_CORRIDOR_TYPES[0]);
  }
  const total = open.reduce((s, t) => s + t.weight, 0);
  let roll = rand() * total;
  for (const t of open) { roll -= t.weight; if (roll <= 0) return t; }
  return open[open.length - 1];
}

/**
 * The narrowest thing the vocabulary can describe.
 *
 * A corridor's WORD carries its ceiling, its props and its authoring width, and
 * `sectionForWidth` labels a passage by the widest section it reaches. So a passage
 * narrower than the narrowest section has no honest word: it gets labelled `squeeze`
 * and the label then OVERSTATES it. Measured: the router floored its mouths at
 * MIN_WALKABLE_WIDTH (1.30m) while a squeeze is 1.55m, so a 2.13m declared opening
 * could sit in a rect stamped 2.20m — a cobweb spun to the word's width hung 7cm wide
 * of the hole it was in.
 *
 * A corridor is therefore at least a squeeze. Narrower openings are not a defect and
 * are not gone — a CRAWL is a deliberate feature (level/anchors.ts: an opening the
 * widest roamer cannot follow you through) — but a crawl is authored as a crawl, not
 * discovered by a corridor coming out too thin.
 */
export const NARROWEST_SECTION = ALL_CORRIDOR_TYPES.reduce(
  (m, t) => Math.min(m, t.width), Infinity);

/**
 * The WORD for a width that has already been decided.
 *
 * ── WHY THE LABEL FOLLOWS THE GEOMETRY AND NOT THE OTHER WAY ROUND ───────────
 *
 * docs/LINKS-V3.md rule 2: width has ONE owner, the link. A link negotiates each
 * mouth against its own wall, so the width it ends up with is whatever BOTH walls
 * could actually give — a continuous quantity, not one of three numbers. Meanwhile
 * `corridorTypeFor*` picks a section BEFORE routing, because the router needs a
 * width to ask for.
 *
 * Those two facts cannot both be respected by stamping the requested section on the
 * result. Measured with space-based selection on: 477 of 1569 corridors were built
 * to a different width than their word claimed, worst case 2.10m out — a corridor
 * stamped `gallery` and built at 1.50m would get a 4.60m ceiling over a slot.
 *
 * So the word is a BAND, applied afterwards: the widest section whose width the
 * passage actually reaches. The label then cannot lie, and it errs downward —
 * `understating` a 1.94m passage as a squeeze gives it a 2.30m ceiling rather than
 * a 3.00m one, and a prop authored for a squeeze fits in something wider. Erring
 * upward would put daylight over a doorway, the same reason DEFAULT_PASSAGE_H takes
 * the low end.
 *
 * Nothing narrower than the narrowest section should reach here — the router floors
 * every mouth at MIN_WALKABLE_WIDTH — but if one does it gets the narrowest word
 * rather than no word, because a corridor with no section has no ceiling and no
 * props.
 */
export function sectionForWidth(width: number): CorridorType {
  let best: CorridorType | null = null;
  for (const t of ALL_CORRIDOR_TYPES) {
    if (t.width <= width + 1e-6 && (!best || t.width > best.width)) best = t;
  }
  return best ?? ALL_CORRIDOR_TYPES.reduce((m, t) => (t.width < m.width ? t : m), ALL_CORRIDOR_TYPES[0]);
}

/** Look-up by id, for a spec that stored the word rather than the numbers. */
export function corridorType(id: CorridorTypeId | undefined): CorridorType {
  return (id && CORRIDOR_TYPES[id]) || CORRIDOR_TYPES.passage;
}
